# Generated by Django 2.1 on 2019-03-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='makePost',
            new_name='Post',
        ),
    ]
